import {
    Baby,
    Banknote,
    Briefcase,
    Broom,
    Bus,
    Car,
    CircleDollarSign,
    CirclePlus,
    Coins,
    CreditCard,
    Dumbbell,
    Ellipsis,
    Gamepad2,
    Gift,
    GraduationCap,
    HandCoins,
    HeartPulse,
    House,
    Key,
    Landmark,
    Laptop,
    PawPrint,
    PiggyBank,
    Plane,
    Receipt,
    Shirt,
    ShoppingBag,
    ShoppingBasket,
    ShoppingCart,
    Smartphone,
    Stethoscope,
    Utensils,
    Wallet,
    Wrench,
} from '@lucide/vue';
import type { LucideIcon } from '@lucide/vue';

/**
 * Nama ikon dari backend dipetakan ke komponennya di sini, bukan di halaman,
 * supaya kategori baru cukup ditambahkan sekali.
 */
const icons: Record<string, LucideIcon> = {
    baby: Baby,
    banknote: Banknote,
    briefcase: Briefcase,
    broom: Broom,
    bus: Bus,
    car: Car,
    'circle-dollar-sign': CircleDollarSign,
    'circle-plus': CirclePlus,
    coins: Coins,
    'credit-card': CreditCard,
    dumbbell: Dumbbell,
    ellipsis: Ellipsis,
    'gamepad-2': Gamepad2,
    gift: Gift,
    'graduation-cap': GraduationCap,
    'hand-coins': HandCoins,
    'heart-pulse': HeartPulse,
    house: House,
    key: Key,
    landmark: Landmark,
    laptop: Laptop,
    'paw-print': PawPrint,
    'piggy-bank': PiggyBank,
    plane: Plane,
    receipt: Receipt,
    shirt: Shirt,
    'shopping-bag': ShoppingBag,
    'shopping-basket': ShoppingBasket,
    'shopping-cart': ShoppingCart,
    smartphone: Smartphone,
    stethoscope: Stethoscope,
    utensils: Utensils,
    wallet: Wallet,
    wrench: Wrench,
};

export function categoryIcon(name: string | null | undefined): LucideIcon {
    return (name && icons[name]) || Ellipsis;
}
