import {
    Baby,
    Banknote,
    Briefcase,
    Broom,
    Bus,
    Candy,
    Car,
    CircleDollarSign,
    CirclePlus,
    Coffee,
    Coins,
    CreditCard,
    CupSoda,
    Droplets,
    Dumbbell,
    Ellipsis,
    Gamepad2,
    Gift,
    Globe,
    GraduationCap,
    HandCoins,
    HeartPulse,
    House,
    Key,
    Landmark,
    Laptop,
    Milk,
    PawPrint,
    PiggyBank,
    Plane,
    Plug,
    Receipt,
    Shirt,
    ShoppingBag,
    ShoppingBasket,
    ShoppingCart,
    Signal,
    Smartphone,
    SoapDispenserDroplet,
    Stethoscope,
    Utensils,
    Wallet,
    Wifi,
    Wrench,
} from '@lucide/vue';
import type { LucideIcon } from '@lucide/vue';

/**
 * Nama ikon dari backend dipetakan ke komponennya di sini, bukan di halaman,
 * supaya kategori baru cukup ditambahkan sekali.
 */
const icons: Record<string, LucideIcon> = {
    baby: Baby,
    banknote: Banknote,
    briefcase: Briefcase,
    broom: Broom,
    bus: Bus,
    candy: Candy,
    car: Car,
    'circle-dollar-sign': CircleDollarSign,
    'circle-plus': CirclePlus,
    coffee: Coffee,
    coins: Coins,
    'credit-card': CreditCard,
    'cup-soda': CupSoda,
    droplets: Droplets,
    dumbbell: Dumbbell,
    ellipsis: Ellipsis,
    'gamepad-2': Gamepad2,
    gift: Gift,
    globe: Globe,
    'graduation-cap': GraduationCap,
    'hand-coins': HandCoins,
    'heart-pulse': HeartPulse,
    house: House,
    key: Key,
    landmark: Landmark,
    laptop: Laptop,
    milk: Milk,
    'paw-print': PawPrint,
    'piggy-bank': PiggyBank,
    plane: Plane,
    plug: Plug,
    receipt: Receipt,
    shirt: Shirt,
    'shopping-bag': ShoppingBag,
    'shopping-basket': ShoppingBasket,
    'shopping-cart': ShoppingCart,
    signal: Signal,
    smartphone: Smartphone,
    'soap-dispenser-droplet': SoapDispenserDroplet,
    stethoscope: Stethoscope,
    utensils: Utensils,
    wallet: Wallet,
    wifi: Wifi,
    wrench: Wrench,
};

export function categoryIcon(name: string | null | undefined): LucideIcon {
    return (name && icons[name]) || Ellipsis;
}
